# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vendorinfo.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vendorInfoPage(object):
    def setupUi(self, vendorInfoPage):
        vendorInfoPage.setObjectName("vendorInfoPage")
        vendorInfoPage.setMinimumWidth(600)
        self.horizontalLayout = QtWidgets.QHBoxLayout(vendorInfoPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.vendorPhoto = QtWidgets.QLabel(vendorInfoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendorPhoto.sizePolicy().hasHeightForWidth())
        sizePolicy.setRetainSizeWhenHidden(True)
        self.vendorPhoto.setSizePolicy(sizePolicy)
        self.vendorPhoto.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.vendorPhoto.setMinimumSize(QtCore.QSize(300, 300))
        self.vendorPhoto.setObjectName("vendorPhoto")
        self.horizontalLayout.addWidget(self.vendorPhoto)
        self.vendorInfo = QtWidgets.QWidget(vendorInfoPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vendorInfo.sizePolicy().hasHeightForWidth())
        self.vendorInfo.setSizePolicy(sizePolicy)
        self.vendorInfo.setObjectName("vendorInfo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.vendorInfo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.basicInfo = QtWidgets.QTableWidget(self.vendorInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.basicInfo.sizePolicy().hasHeightForWidth())
        self.basicInfo.setSizePolicy(sizePolicy)
        self.basicInfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.basicInfo.setTabKeyNavigation(False)
        self.basicInfo.setProperty("showDropIndicator", False)
        self.basicInfo.setDragDropOverwriteMode(False)
        self.basicInfo.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.basicInfo.setShowGrid(False)
        self.basicInfo.setWordWrap(True)
        self.basicInfo.setObjectName("basicInfo")
        self.basicInfo.setColumnCount(1)
        self.basicInfo.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.basicInfo.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.basicInfo.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.basicInfo.setHorizontalHeaderItem(0, item)
        self.basicInfo.horizontalHeader().setVisible(False)
        self.basicInfo.verticalHeader().setVisible(True)
        self.basicInfo.verticalHeaderItem(0).setText("0")
        self.basicInfo.setMaximumSize(QtCore.QSize(16777215, self.basicInfo.rowHeight(0)*2+4))
        self.verticalLayout.addWidget(self.basicInfo)
        self.memuLabel = QtWidgets.QLabel(self.vendorInfo)
        self.memuLabel.setScaledContents(False)
        self.memuLabel.setObjectName("memuLabel")
        self.verticalLayout.addWidget(self.memuLabel)
        self.memuTable = QtWidgets.QTableWidget(self.vendorInfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.memuTable.sizePolicy().hasHeightForWidth())
        self.memuTable.setSizePolicy(sizePolicy)
        self.memuTable.setMinimumSize(QtCore.QSize(0, 0))
        self.memuTable.setSizeIncrement(QtCore.QSize(0, 0))
        self.memuTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.memuTable.setProperty("showDropIndicator", False)
        self.memuTable.setDragDropOverwriteMode(False)
        self.memuTable.setAlternatingRowColors(True)
        self.memuTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.memuTable.setObjectName("memuTable")
        self.memuTable.setColumnCount(2)
        self.memuTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        item = QtWidgets.QTableWidgetItem()
        self.memuTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        item.setFont(font)
        self.memuTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.memuTable.setHorizontalHeaderItem(1, item)
        self.memuTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.memuTable)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.openCalculatorBtn = QtWidgets.QPushButton(self.vendorInfo)
        self.openCalculatorBtn.setObjectName("openCalculatorBtn")
        self.horizontalLayout_2.addWidget(self.openCalculatorBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.vendorInfo)

        self.retranslateUi(vendorInfoPage)
        QtCore.QMetaObject.connectSlotsByName(vendorInfoPage)

    def retranslateUi(self, vendorInfoPage):
        _translate = QtCore.QCoreApplication.translate
        vendorInfoPage.setWindowTitle(_translate("vendorInfoPage", "Form"))
        self.vendorPhoto.setText(_translate("vendorInfoPage", "vendor Photo"))
        self.basicInfo.setSortingEnabled(False)
        item = self.basicInfo.verticalHeaderItem(0)
        item.setText(_translate("vendorInfoPage", "Name"))
        item = self.basicInfo.verticalHeaderItem(1)
        item.setText(_translate("vendorInfoPage", "Opening Time"))
        item = self.basicInfo.horizontalHeaderItem(0)
        item.setText(_translate("vendorInfoPage", "info"))
        self.memuLabel.setText(_translate("vendorInfoPage", "memu"))
        item = self.memuTable.horizontalHeaderItem(0)
        item.setText(_translate("vendorInfoPage", "Food"))
        item = self.memuTable.horizontalHeaderItem(1)
        item.setText(_translate("vendorInfoPage", "Price"))
        self.openCalculatorBtn.setText(_translate("vendorInfoPage", "Queue Time Calculator"))
